users = [
    {'username': 'user1', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user2', 'password': 'megaP4SS$0RD', 'role': 'user'},

    {'username': 'user3', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user4', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user5', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user6', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user7', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user8', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user9', 'password': 'superP4S$W0RD', 'role': 'superuser'},
    {'username': 'user10', 'password': 'superP4$SW0RD', 'role': 'superuser'},
    {'username': 'user11', 'password': 'superP4$SW0RD', 'role': 'superuser'},

    {'username': 'user21', 'password': 'megaP4S$$W0RD', 'role': 'user'},
    {'username': 'user22', 'password': 'megaP4S$W0RD', 'role': 'user'},
    {'username': 'user23', 'password': 'megaP4S$W0RD', 'role': 'user'},
    {'username': 'user24', 'password': 'megaP4SW$0RD', 'role': 'user'},
    {'username': 'user25', 'password': 'megaP4SW0$RD', 'role': 'user'},
    {'username': 'user26', 'password': 'megaP4SW0R$D', 'role': 'user'},
    {'username': 'user27', 'password': 'megaP4SW0$RD', 'role': 'user'},
    {'username': 'user28', 'password': 'megaP4SW$0RD', 'role': 'user'},
    {'username': 'user29', 'password': 'megaP4S$W0RD', 'role': 'user'},
    {'username': 'user30', 'password': 'megaP4SW0$RD', 'role': 'user'},
    {'username': 'user31', 'password': 'megaP4SW0$RD', 'role': 'user'},
]
